source: site
destination: www
markdown: rdiscount
permalink: date
server_port: 2222
rsync:
  options:
    - "-rclv"
    - "--delete-after"
  excludes:
    - ".*.swp"
    - "*~"
    - ".svn"
    - "/docs/"
  dest:
    host: rubyforge.org
    path: "/var/www/gforge-projects/ronin"
