source: site
destination: www
markdown: rdiscount
permalink: date
server_port: 2222
libraries:
  -
    slug: ronin
    name: Ronin
    version: 0.3.0
    description: A Ruby platform for exploit development and security research.
  -
    slug: ronin-dorks
    name: Ronin Dorks
    version: 0.1.3
    description: A Ruby library for Ronin that provides support for various Google (tm) Dorks and Hacking functionality.
  -
    slug: ronin-exploits
    name: Ronin Exploits
    version: 0.3.1
    description: A Ruby library for Ronin that provides exploitation and payload crafting functionality.
  -
    slug: ronin-gen
    name: Ronin Gen
    version: 0.2.0
    description: A Ruby library for Ronin that provides various generators.
  -
    slug: ronin-php
    name: Ronin PHP
    version: 0.1.4
    description: A Ruby library for Ronin that provides support for PHP related security tasks.
  -
    slug: ronin-scanners
    name: Ronin Scanners
    version: 0.1.4
    description: A Ruby library for Ronin that provides Ruby interfaces to various third-party security scanners.
  -
    slug: ronin-sql
    name: Ronin SQL
    version: 0.2.4
    description: A Ruby library for Ronin that provids support for SQL related security tasks.
  -
    slug: ronin-web
    name: Ronin Web
    version: 0.2.1
    description: A Ruby library for Ronin that provides support for web scraping and spidering functionality.
rsync:
  options:
    - "-rclv"
    - "--delete-after"
  excludes:
    - ".*.swp"
    - "*~"
    - ".svn"
    - "/docs/"
  dest:
    host: rubyforge.org
    path: "/var/www/gforge-projects/ronin"
