auto: true
server: true
server_port: 2222
markdown: rdiscount
pygments: true
permalink: date
libraries:
  -
    slug: ronin-support
    name: Ronin Support
    version: 0.1.0.pre3
    description: A support library for Ronin.
  -
    slug: ronin
    name: Ronin
    version: 1.0.0.pre4
    description: A Ruby platform for exploit development and security research.
  -
    slug: ronin-gen
    name: Ronin Gen
    version: 1.0.0.pre3
    description: A Ruby library for Ronin that provides various generators.
  -
    slug: ronin-dorks
    name: Ronin Dorks
    version: 0.1.3
    description: A Ruby library for Ronin that provides support for various Google (tm) Dorks and Hacking functionality.
  -
    slug: ronin-exploits
    name: Ronin Exploits
    version: 0.3.1
    description: A Ruby library for Ronin that provides exploitation and payload crafting functionality.
  -
    slug: ronin-php
    name: Ronin PHP
    version: 0.1.4
    description: A Ruby library for Ronin that provides support for PHP related security tasks.
  -
    slug: ronin-scanners
    name: Ronin Scanners
    version: 0.1.4
    description: A Ruby library for Ronin that provides Ruby interfaces to various third-party security scanners.
  -
    slug: ronin-sql
    name: Ronin SQL
    version: 0.2.4
    description: A Ruby library for Ronin that provids support for SQL related security tasks.
  -
    slug: ronin-web
    name: Ronin Web
    version: 0.2.1
    description: A Ruby library for Ronin that provides support for web scraping and spidering functionality.
  -
    slug: ronin-metasploit
    name: Ronin Metasploit
    version: 0.1.0
    description: A Ronin library which provides support for accessing The Metasploit Framework.
    dev: true
