source: site
destination: www
markdown: rdiscount
permalink: date
server_port: 2222
libraries:
  ronin:
    name: Ronin
    downloads: 0.3.0
  ronin-dorks:
    name: Ronin Dorks
    version: 0.1.3
  ronin-exploits:
    name: Ronin Exploits
    version: 0.3.1
  ronin-gen:
    name: Ronin Gen
    version: 0.2.0
  ronin-php:
    name: Ronin PHP
    version: 0.1.4
  ronin-scanners:
    name: Ronin Scanners
    version: 0.1.4
  ronin-sql:
    name: Ronin SQL
    version: 0.2.4
  ronin-web:
    name: Ronin Web
    version: 0.2.1
rsync:
  options:
    - "-rclv"
    - "--delete-after"
  excludes:
    - ".*.swp"
    - "*~"
    - ".svn"
    - "/docs/"
  dest:
    host: rubyforge.org
    path: "/var/www/gforge-projects/ronin"
