---
:project:
  :author: Postmodern
  :email: postmodern.mod3 at gmail.com
  :name: ronin
  :title: Ronin
  :desc: Ronin is a Ruby platform designed for information security and data exploration tasks. Ronin allows for the rapid development and distribution of code over many of the common Source-Code-Management (SCM) systems.
  :user: postmodern
  :host: rubyforge.org
  :webroot: "/var/www/gforge-projects/ronin"
  :groupid: 3798
  :svn: "http://ronin.rubyforge.org/svn"
  :bugs: 14630
  :support: 14631
  :patches: 14632
  :features: 14633
:rsync:
  :options:
    - "-rclv"
    - "--delete-after"
  :excludes:
    - ".*.swp"
    - "*~"
    - ".svn"
    - "/docs/"
:pages:
  - index
  - faq
  - libraries
  - asm/index
  - dorks/index
  - exploits/index
  - gen/index
  - html/index
  - sql/index
  - php/index
  - scanners/index
  - web/index
  - howtos/index
  - howtos/everyday_ronin
  - howtos/living_on_the_edge
  - howtos/ronin_on_debian
  - talks/index
  - talks/postmodern
  - talks/publishing_and_mayhem
  - contribute/index
  - contribute/style
  - contact
  - example
